import { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Messenger Clone",
  description: "A Real-Time Messenger Clone using Next.js 14.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "messenger clone",
    "chat app",
    "realtime",
    "next-auth",
    "zustand",
    "socket.io",
    "clsx",
    "react-hot-toast",
    "next-cloudinary",
    "headlessui",
    "nosql",
    "bcrypt",
    "mongodb",
    "prisma",
    "react-icons",
    "react-select",
    "react-spinners",
    "axios",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Sanidhya Kumar Verma",
    url: "https://github.com/sanidhyy",
  },
} as const;
